language: python
python:
  - "2.7"
env: NOSE_WITH_OPENSTACK=1
     NOSE_OPENSTACK_COLOR=1
     NOSE_OPENSTACK_RED=0.05
     NOSE_OPENSTACK_YELLOW=0.025
     NOSE_OPENSTACK_SHOW_ELAPSED=1
     NOSE_OPENSTACK_STDOUT=1
install:
  - pip install -r test_requirements.txt --use-mirror
  - pip install flake8 --use-mirrors
  - pip install -q . --use-mirrors
before_script:
  - flake8 --show-source --ignore=E125 --statistics akanda
script: python akanda/horizon/manage.py test tests